#!/bin/sh
#
#   ubucdimage - provides an easy way to sync ISO files from an Ubuntu CD
#                image mirror.
#
#   Copyright (C) 2006 - 2009 Nafallo Bjälevik
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

if [ ! -f /etc/ubumirror.conf ]; then
	echo "File /etc/ubumirror.conf does not exist!"
	exit 2
fi

. /etc/ubumirror.conf

LOCK="${UBUCDI_DIR}/Archive-Update-in-Progress-${HOSTNAME}"

UBUALTN="${UBUCDI_DIR}/daily/"
UBULIVE="${UBUCDI_DIR}/daily-live/"

# Get in the right directory and set the umask to be group writable
cd $HOME
umask 022

# Check to see if another sync is in progress
if lockfile -! -l 43200 -r 0 "$LOCK"; then
  echo $HOSTNAME is unable to start rsync, lock file exists
  exit 1
fi
trap 'rm -f $LOCK > /dev/null 2>&1; echo -n "Done at " >> $LOGDIR/ubucdimage.log; date >> $LOGDIR/ubucdimage.log; savelog -n $LOGDIR/ubucdimage.log > /dev/null' EXIT

echo -n "Starting at " >> $LOGDIR/ubucdimage.log
date >> $LOGDIR/ubucdimage.log

set +e
echo "Syncing alternate ISOs..." >> $LOGDIR/ubucdimage.log
rsync -av --partial --timeout=600 \
      --bwlimit=$SPEED \
	  $UBUCDI_EXCLUDE \
      $UBUCDI_MIRROR/daily/current/ $UBUALTN >> $LOGDIR/ubucdimage.log 2>&1

if [ $? -ne 0 ]; then
        ( echo "Eeek. Ubuntu alternate rsync broke down... Check logs.."; \
          egrep '^write failed|@ERROR' $LOGDIR/ubucdimage.log ) | mail -s "Ubuntu cdimage sync failed" $EMAIL
        echo "Eeek. Ubuntu alternate rsync broke down..." >> $LOGDIR/ubucdimage.log
        exit 2
fi

echo -n "Done at " >> $LOGDIR/ubucdimage.log
date >> $LOGDIR/ubucdimage.log && echo "" >> $LOGDIR/ubucdimage.log
echo "Syncing desktop ISOs..." >> $LOGDIR/ubucdimage.log
rsync -av --partial --timeout=600 \
      --bwlimit=$SPEED \
      $UBUCDI_EXCLUDE \
      $UBUCDI_MIRROR/daily-live/current/ $UBULIVE >> $LOGDIR/ubucdimage.log 2>&1

if [ $? -ne 0 ]; then
        ( echo "Eeek. Ubuntu desktop rsync broke down... Check logs.."; \
          egrep '^write failed|@ERROR' $LOGDIR/ubucdimage.log ) | mail -s "Ubuntu cdimage sync failed" $EMAIL
        echo "Eeek. Ubuntu desktop rsync broke down..." >> $LOGDIR/ubucdimage.log
        exit 2
fi

rm -f $LOCK > /dev/null 2>&1
