#!/bin/sh
#
#   ubucdimage - provides an easy way to sync daily ISO files from an
#                Ubuntu CD image mirror.
#
#   Copyright (C) 2006 - 2009 Nafallo Bjälevik
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

if [ ! -f /etc/ubumirror.conf ]; then
	echo "File /etc/ubumirror.conf does not exist!"
	exit 2
fi

. /etc/ubumirror.conf

LOCK="${UBUCDI_DIR}/Archive-Update-in-Progress-${HOSTNAME}"

if [ -z "$UBUCDI_DIR" ]; then
    echo -n "No Ubuntu cdimage target directory (UBUCDI_DIR) set in "
    echo "/etc/ubumirror.conf."
    exit 2
fi

UBUALTN="${UBUCDI_DIR}/daily/"
UBULIVE="${UBUCDI_DIR}/daily-live/"

# Get in the right directory and set the umask to be group writable
cd $HOME
umask 022

# Check to see if another sync is in progress
if ! ( set -o noclobber; echo "$$" > "${LOCK}") 2> /dev/null; then
        if ! $(kill -0 $(cat ${LOCK}) 2>/dev/null); then
                # Process does either not exist or is not owned by us.
                echo "$$" > "${LOCK}"
        else
                echo "Unable to start rsync, lock file still exists, PID $(cat ${LOCK})."
                exit 1
        fi
fi

trap 'rm -f $LOCK > /dev/null 2>&1; echo "Done at $(date)" >> $LOGDIR/ubucdimage.log; savelog -c 28 -n $LOGDIR/ubucdimage.log > /dev/null' EXIT

echo "Starting at $(date)" >> $LOGDIR/ubucdimage.log

set +e
echo "Syncing alternate ISOs..." >> $LOGDIR/ubucdimage.log
rsync -av --partial --timeout=600 \
      --bwlimit=$SPEED \
	  $UBUCDI_EXCLUDE \
      $UBUCDI_MIRROR/daily/current/ $UBUALTN >> $LOGDIR/ubucdimage.log 2>&1

if [ $? -ne 0 ]; then
        ( echo "Eeek. Ubuntu alternate rsync broke down... Check logs.."; \
          egrep '^write failed|@ERROR' $LOGDIR/ubucdimage.log ) | mail -s "Ubuntu cdimage sync failed" $EMAIL
        echo "Eeek. Ubuntu alternate rsync broke down..." >> $LOGDIR/ubucdimage.log
        exit 2
fi

echo "Done at $(date)" >> $LOGDIR/ubucdimage.log

echo "Syncing desktop ISOs..." >> $LOGDIR/ubucdimage.log
rsync -av --partial --timeout=600 \
      --bwlimit=$SPEED \
      $UBUCDI_EXCLUDE \
      $UBUCDI_MIRROR/daily-live/current/ $UBULIVE >> $LOGDIR/ubucdimage.log 2>&1

if [ $? -ne 0 ]; then
        ( echo "Eeek. Ubuntu desktop rsync broke down... Check logs.."; \
          egrep '^write failed|@ERROR' $LOGDIR/ubucdimage.log ) | mail -s "Ubuntu cdimage sync failed" $EMAIL
        echo "Eeek. Ubuntu desktop rsync broke down..." >> $LOGDIR/ubucdimage.log
        exit 2
fi

rm -f $LOCK > /dev/null 2>&1
