#! /bin/bash
set -e

if [ ! -f $HOME/ubumirror.conf ]; then
	echo "No $HOME/ubumirror.conf!"
	exit
fi

. $HOME/ubumirror.conf

if [ ! "$1" = "" ]; then
  SPEED="$1"
fi

#HOSTNAME=`hostname -f`
HOSTNAME=mirror.magicalforest.se

LOCK="${CDIMAGE}/Archive-Update-in-Progress-${HOSTNAME}"

ISO="${CDIMAGE}/daily/"

# Get in the right directory and set the umask to be group writable
# 
cd $HOME
umask 022

# Check to see if another sync is in progress
if lockfile -! -l 43200 -r 0 "$LOCK"; then
  echo $HOSTNAME is unable to start rsync, lock file exists
  exit 1
fi
trap 'rm -f $LOCK > /dev/null 2>&1; echo -n "Done at " >> $LOGDIR/ubucd.log; date >> $LOGDIR/ubucd.log; savelog -n $LOGDIR/ubucd.log > /dev/null' EXIT

echo -n "Starting at " >> $LOGDIR/ubucd.log
date >> $LOGDIR/ubucd.log

set +e
echo "Syncing files needed to use jigit..." >> $LOGDIR/ubucd.log
rsync -rltvHz --timeout=600 --bwlimit=$SPEED \
      --exclude *.iso --exclude jigit/ \
      $CD_EXCLUDE \
      $CD_HOST::$CD_DIR/daily/current/ $ISO >> $LOGDIR/ubucd.log 2>&1

if [ `grep -c '^total size is' $LOGDIR/ubucd.log ` -ne 1 ]; then
        ( echo "Eeek. Ubuntu jigdo rsync broke down... Check logs.."; \
          egrep '^write failed|@ERROR' $LOGDIR/ubucd.log ) | mail -s "Ubuntu jigdo sync failed" $EMAIL
        echo "Eeek. Ubuntu jigdo rsync broke down..." >> $LOGDIR/ubucd.log
        exit 1
fi

echo -n "Done at " >> $LOGDIR/ubucd.log
date >> $LOGDIR/ubucd.log && echo "" >> $LOGDIR/ubucd.log
echo "Generating images for Install CDs..." >> $LOGDIR/ubucd.log

for a in ${ISO}*.jigdo; do
	b=`basename $a .jigdo`
	echo -n "jigiting ${b}.iso..." >> $LOGDIR/ubucd.log
	mkimage -m Debian=$ARCHIVE -f ${ISO}MD5SUMS -j ${ISO}${b}.jigdo -t ${ISO}${b}.template -o ${ISO}.${b}.iso >> $LOGDIR/ubucd.log 2>/dev/null
	if test -s ${ISO}.${b}.iso; then
		mv ${ISO}.${b}.iso ${ISO}${b}.iso;
		echo " Successful!" >> $LOGDIR/ubucd.log;
	else
		echo " Failed!" >> $LOGDIR/ubucd.log;
	fi
done

echo -n "Done at " >> $LOGDIR/ubucd.log
date >> $LOGDIR/ubucd.log && echo "" >> $LOGDIR/ubucd.log
echo "Syncing Live CDs..." >> $LOGDIR/ubucd.log

rsync -rltvHz --partial --timeout=600 --bwlimit=$SPEED \
      $CD_EXCLUDE \
      $CD_HOST::$CD_DIR/daily-live/current/ $CDIMAGE/daily-live/ >> $LOGDIR/ubucd.log 2>&1

if [ `grep -c '^total size is' $LOGDIR/ubucd.log ` -ne 2 ]; then
        ( echo "Eeek. Ubuntu livecd rsync broke down... Check logs.."; \
          egrep '^write failed|@ERROR' $LOGDIR/ubucd.log ) | mail -s "Ubuntu livecd sync failed" $EMAIL
        echo "Eeek. Ubuntu livecd rsync broke down..." >> $LOGDIR/ubucd.log
        exit 2
fi

rm -f $LOCK > /dev/null 2>&1
