#!/bin/sh
set -e

if [ ! -f $HOME/ubumirror.conf ]; then
	echo "No $HOME/ubumirror.conf!"
	exit
fi

. $HOME/ubumirror.conf

# Set your FQDN here
HOSTNAME=`hostname -f`

LOCK="${CDIMAGE}/Archive-Update-in-Progress-${HOSTNAME}"

# Get in the right directory and set the umask to be group writable
cd $HOME
umask 022

# Check to see if another sync is in progress
if lockfile -! -l 43200 -r 0 "$LOCK"; then
  echo $HOSTNAME is unable to start rsync, lock file exists
  exit 1
fi
trap 'rm -f $LOCK > /dev/null 2>&1; echo -n "Done at " >> $LOGDIR/ubudvd.log; date >> $LOGDIR/ubudvd.log; savelog -n $LOGDIR/ubudvd.log > /dev/null' EXIT

echo -n "Starting at " >> $LOGDIR/ubudvd.log
date >> $LOGDIR/ubudvd.log

set +e
echo "Syncing ISOs..." >> $LOGDIR/ubudvd.log
rsync -av --partial --timeout=600 \
      $DVD_EXCLUDE \
      $DVD_HOST::$DVD_DIR/ $CDIMAGE >> $LOGDIR/ubudvd.log 2>&1

if [ `grep -c '^total size is' $LOGDIR/ubudvd.log ` -ne 1 ]; then
        ( echo "Eeek. Ubuntu iso rsync broke down... Check logs.."; \
          egrep '^write failed|@ERROR' $LOGDIR/ubudvd.log ) | mail -s "Ubuntu dvd sync failed" $EMAIL
        echo "Eeek. Ubuntu iso rsync broke down..." >> $LOGDIR/ubudvd.log
        exit 2
fi

echo -n "Done at " >> $LOGDIR/ubudvd.log
date >> $LOGDIR/ubudvd.log && echo "" >> $LOGDIR/ubudvd.log
rm -f $LOCK > /dev/null 2>&1
date -u > "${CDIMAGE}/.trace/${HOSTNAME}"
