#!/bin/sh
#
#   ubudvd - provides an easy way to sync DVD images from an Ubuntu DVD
#            mirror.
#
#   Copyright (C) 2006 - 2009 Nafallo Bjälevik
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

if [ ! -f /etc/ubumirror.conf ]; then
	echo "File /etc/ubumirror.conf does not exist!"
	exit
fi

. /etc/ubumirror.conf

LOCK="${UMDVD}/Archive-Update-in-Progress-${HOSTNAME}"

# Get in the right directory and set the umask to be group writable
cd $HOME
umask 022

# Check to see if another sync is in progress
if lockfile -! -l 43200 -r 0 "$LOCK"; then
  echo $HOSTNAME is unable to start rsync, lock file exists
  exit 1
fi
trap 'rm -f $LOCK > /dev/null 2>&1; echo -n "Done at " >> $LOGDIR/ubudvd.log; date >> $LOGDIR/ubudvd.log; savelog -n $LOGDIR/ubudvd.log > /dev/null' EXIT

echo -n "Starting at " >> $LOGDIR/ubudvd.log
date >> $LOGDIR/ubudvd.log

set +e
echo "Syncing ISOs..." >> $LOGDIR/ubudvd.log
rsync -av --partial --timeout=600 \
      --bwlimit=$SPEED \
      $UMD_EXCLUDE \
      $UMD_MIRROR $UMDVD >> $LOGDIR/ubudvd.log 2>&1

if [ $? -ne 0 ]; then
        ( echo "Eeek. Ubuntu iso rsync broke down... Check logs.."; \
          egrep '^write failed|@ERROR' $LOGDIR/ubudvd.log ) | mail -s "Ubuntu dvd sync failed" $EMAIL
        echo "Eeek. Ubuntu iso rsync broke down..." >> $LOGDIR/ubudvd.log
        exit 2
fi

echo -n "Done at " >> $LOGDIR/ubudvd.log
date >> $LOGDIR/ubudvd.log && echo "" >> $LOGDIR/ubudvd.log
rm -f $LOCK > /dev/null 2>&1
date -u > "${UMDVD}/.trace/${HOSTNAME}"
