#! /bin/sh
set -e

if [ ! -f $HOME/ubumirror.conf ]; then
	echo "No $HOME/ubumirror.conf!"
	exit
fi

. $HOME/ubumirror.conf

if [ ! "$1" = "" ]; then
  SPEED="$1"
fi

#HOSTNAME=`hostname -f`
HOSTNAME=mirror.magicalforest.se

LOCK="${ARCHIVE}/Archive-Update-in-Progress-${HOSTNAME}"

# Get in the right directory and set the umask
# 
cd $HOME
umask 022

# Check to see if another sync is in progress
if lockfile -! -l 43200 -r 0 "$LOCK"; then
  echo ${HOSTNAME} is unable to start rsync, lock file exists
  exit 1
fi
trap 'rm -f $LOCK > /dev/null 2>&1; echo -n "Done at " >> $LOGDIR/ubusync.log; date >> $LOGDIR/ubusync.log; savelog -n $LOGDIR/ubusync.log > /dev/null' EXIT

echo -n "Starting at " > $LOGDIR/ubusync.log
date >> $LOGDIR/ubusync.log

set +e
echo "First sync without dists and indices..." >> $LOGDIR/ubusync.log
rsync -rLtvHz --timeout=600 --partial --bwlimit=$SPEED \
      --delete --delete-after --exclude "*.tar.gz" \
      --exclude "indices/" --exclude "dists/" \
      --exclude "Archive-Update-in-Progress-${HOSTNAME}" \
      --exclude "project/trace/${HOSTNAME}" \
      $AR_EXCLUDE \
      $AR_HOST::$AR_DIR/ $ARCHIVE/ >> $LOGDIR/ubusync.log 2>&1

if [ `grep -c '^total size is' $LOGDIR/ubusync.log ` -ne 1 ]; then
	( echo "Eeek. First rsync to ubuntu broke down... Check logs.."; \
	  egrep '^write failed|@ERROR' $LOGDIR/ubusync.log ) | mail -s "Ubuntu sync failed" $EMAIL
	echo "Eeek. First rsync to ubuntu broke down..." >> $LOGDIR/ubusync.log
	exit 1
fi
echo -n "Done at " >> $LOGDIR/ubusync.log
date >> $LOGDIR/ubusync.log && echo "" >> $LOGDIR/ubusync.log

echo "Second sync without pool..." >> $LOGDIR/ubusync.log
rsync -rltvHz --timeout=600 --partial --bwlimit=$SPEED \
      --delete --delete-after --exclude "pool/" \
      --exclude "Archive-Update-in-Progress-${HOSTNAME}" \
      --exclude "project/trace/${HOSTNAME}" \
      $AR_EXCLUDE \
      $AR_HOST::$AR_DIR/ $ARCHIVE/ >> $LOGDIR/ubusync.log 2>&1

if [ `grep -c '^total size is' $LOGDIR/ubusync.log ` -ne 2 ]; then
	( echo "Eeek. Second rsync to ubuntu broke down... Check logs.."; \
	  grep '@ERROR' $LOGDIR/ubusync.log ) | mail -s "Ubuntu sync failed" $EMAIL
	echo "Eeek. Second rsync to ubuntu broke down..." >> $LOGDIR/ubusync.log
	exit 2
fi

find $ARCHIVE/ -type l -xtype l | xargs -r rm
rm -f $LOCK > /dev/null 2>&1
date -u > "${ARCHIVE}/project/trace/${HOSTNAME}"
